### ISSUE TITLE
Error in the pipeline

### ISSUE THREAD

**Issue by EvgeniiChaikin** [SWIFTSIM/pipeline#16]
@JBorrow, following the latest updates when I run the pipeline it gives me the following error

```
swift-pipeline -C /cosma7/data/dp004/dc-chai1/pipeline-configs/colibre -c halo_0623.properties.0 -s colibre_0623.hdf5 -d -o ../L12_z2_cold
Traceback (most recent call last):
  File "/cosma/local/Python/3.6.5/bin/swift-pipeline", line 135, in <module>
    from swiftpipeline.config import Config
  File "/cosma7/data/dp004/dc-chai1/pipeline/swiftpipeline/config.py", line 84, in <module>
    class Config(object):
ValueError: 'scripts' in __slots__ conflicts with class variable
```

Perhaps I need to update the config file or do something else?

Using the pipeline in detached mode with the `e776aded7e619c7ec47653613c94dd31d2a3be3b` commit solves the problem.

**Comment by JBorrow** [comment]
Thanks for catching this! Remember to uninstall your user-installed version once this is fixed. Fixed in https://github.com/SWIFTSIM/pipeline/commit/f4c9f82f9e0221c32d0eca3a55cce2034bc64752
